[bell]
animation = "EaseOutExpo"
color = "#666666"
duration = 200

[colors]
draw_bold_text_with_bright_colors = false

[font]
size = 16.0
normal = { family = "SFMono Nerd Font Mono", style = "Regular" }

[scrolling]
history = 10000
multiplier = 1

[terminal.shell]
program = "/opt/homebrew/bin/fish"
args = ["--login"]

[window]
dimensions = { columns = 82, lines = 24 }
padding = { x = 10, y = 10 }
decorations = "buttonless"
dynamic_padding = false
option_as_alt = "OnlyLeft"

[general]
import = ["~/.config/alacritty/nord.toml"]

[terminal]
